// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASPP-z39gey5kGoCL_pKdyW6GCuez0WUo',
    appId: '1:856522879081:web:f04ffaee713a343bbc32f8',
    messagingSenderId: '856522879081',
    projectId: 'music-storage-d79b2',
    authDomain: 'music-storage-d79b2.firebaseapp.com',
    storageBucket: 'music-storage-d79b2.firebasestorage.app',
    measurementId: 'G-ZWBKDXWLXT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB56n7shozvBJmp4GQJtye9ColKdLZo7pY',
    appId: '1:856522879081:ios:5e83a2d98d5137e0bc32f8',
    messagingSenderId: '856522879081',
    projectId: 'music-storage-d79b2',
    storageBucket: 'music-storage-d79b2.firebasestorage.app',
    androidClientId: '856522879081-us214ekrkko9hkubgc43b384adv77unf.apps.googleusercontent.com',
    iosClientId: '856522879081-otvorfggatqof527q15ijjp8hj05do1d.apps.googleusercontent.com',
    iosBundleId: 'jp.sessionconcierge.trackcabinet',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNc6yWj30w2T9mmNPqpm4fURN1XQj7fZY',
    appId: '1:856522879081:android:0cdd0eedd4d9be1fbc32f8',
    messagingSenderId: '856522879081',
    projectId: 'music-storage-d79b2',
    storageBucket: 'music-storage-d79b2.firebasestorage.app',
  );
}
